SUPPORTED_LANGUAGES = ("zh-TW", "en")

SETUP_GUIDES = {
    "zh-TW": (
        "1. 按「一鍵診斷」處理 runtime，進階模式也可手動匯入 runtime。\n"
        "2. 按「一鍵診斷」下載模型，或把模型 zip 解壓到 models 資料夾。\n"
        "3. 選擇「喇叭來源」、「麥克風來源」與「TTS 輸出」。\n"
        "4. 本工具「TTS 輸出」選虛擬音訊線輸出，通話軟體麥克風選對應的輸入。\n"
        "5. 選場景會自動套用；進階模式可調模型、runtime 路徑與自動優化。\n"
        "6. 開始前先跑「測試麥克風」與「測試虛擬麥克風」；進階模式可再測字幕、喇叭與 TTS。"
    ),
    "en": (
        "1. Run diagnostics to set up the runtime; advanced mode can also import one manually.\n"
        "2. Run diagnostics to download a model, or extract a model zip into the models folder.\n"
        "3. Select the speaker source, microphone source, and TTS output.\n"
        "4. Route TTS to the virtual audio output and select its matching input in the call app.\n"
        "5. Selecting a scenario applies its settings; advanced mode exposes models, runtime paths, and optimization.\n"
        "6. Test the microphone and virtual microphone before starting; advanced mode can also test subtitles, speaker, and TTS."
    ),
}


ENGLISH = {
    "介面語言": "Interface language",
    "來源語言": "Source language",
    "目標語言": "Target language",
    "翻譯服務": "Translation provider",
    "翻譯風格": "Translation style",
    "TTS 服務": "TTS provider",
    "場景": "Scenario",
    "效能模式": "Performance mode",
    "本機翻譯 URL": "Local translation URL",
    "翻譯後端版本": "Translation backend revision",
    "OpenAI 模型": "OpenAI model",
    "模型": "Model",
    "ASR 裝置": "ASR device",
    "運算精度": "Compute type",
    "喇叭來源": "Speaker source",
    "麥克風來源": "Microphone source",
    "TTS 輸出": "TTS output",
    "虛擬麥克風檢查輸入": "Virtual microphone check input",
    "對方翻譯播放輸出": "Remote translation playback output",
    "TTS 速度": "TTS rate",
    "虛擬麥克風語音音量": "Virtual microphone speech volume",
    "本機翻譯音量": "Local translation volume",
    "TTS 聲音": "TTS voice",
    "Google TTS 聲音": "Google TTS voice",
    "OpenAI TTS 模型": "OpenAI TTS model",
    "OpenAI TTS 聲音": "OpenAI TTS voice",
    "Google 專案": "Google project",
    "Google JSON": "Google JSON",
    "術語表 JSON": "Glossary JSON",
    "最大語句秒數": "Maximum segment seconds",
    "語音閾值": "Speech threshold",
    "字幕透明度": "Subtitle opacity",
    "字幕字級": "Subtitle font size",
    "字幕停留秒數": "Subtitle hold seconds",
    "紀錄內容": "Log content",
    "紀錄保留天數": "Log retention days",
    "紀錄容量上限 MB": "Log size limit MB",
    "紀錄資料夾": "Log folder",
    "runtime 資料夾": "Runtime folder",
    "選擇": "Browse",
    "套用": "Apply",
    "列出": "List",
    "開啟 runtime 資料夾": "Open runtime folder",
    "匯入已解壓 runtime": "Import extracted runtime",
    "下載上游 runtime": "Download upstream runtime",
    "顯示字幕": "Show subtitles",
    "字幕最上層": "Keep subtitles on top",
    "顯示語言": "Show languages",
    "顯示原文": "Show original text",
    "顯示譯文": "Show translation",
    "播放翻譯語音": "Play translated speech",
    "擷取喇叭": "Capture speaker",
    "擷取麥克風": "Capture microphone",
    "進階設定": "Advanced settings",
    "儲存對話紀錄": "Save conversation logs",
    "播放對方翻譯": "Play remote translation",
    "虛擬麥克風啟動時靜音": "Mute virtual microphone on start",
    "輸出到虛擬麥克風": "Output to virtual microphone",
    "設定精靈": "Setup guide",
    "重新整理": "Refresh",
    "交換語言": "Swap languages",
    "套用場景": "Apply scenario",
    "自動優化": "Auto optimize",
    "推薦模型": "Recommend model",
    "下載模型": "Download model",
    "取消模型下載": "Cancel model download",
    "一鍵診斷": "Run diagnostics",
    "開啟 runtime 資料夾 / 下載 runtime": "Open runtime folder / download runtime",
    "測試喇叭 / 測試麥克風 / 測試虛擬麥克風": "Test speaker / microphone / virtual microphone",
    "設定指南": "Setup guide",
    "錯誤": "Error",
    "警告": "Warning",
    "資訊": "Information",
    "提示": "Information",
    "目前沒有發現需要處理的設定問題。": "No configuration issues need attention.",
    "問題名稱：{title}": "Issue: {title}",
    "可能原因：{detail}": "Possible cause: {detail}",
    "自動檢查結果：{code}": "Diagnostic code: {code}",
    "建議修復步驟：{fix}": "Recommended fix: {fix}",
    "一鍵修復按鈕：{action}": "Quick fix: {action}",
    "進階日誌：{path}": "Detailed log: {path}",
    "首次診斷失敗：{error}": "Initial diagnostics failed: {error}",
    "首次設定": "Initial setup",
    "正在執行診斷": "Running diagnostics",
    "診斷結果": "Diagnostic results",
    "診斷失敗": "Diagnostics failed",
    "正在列出 Windows TTS 聲音": "Listing Windows TTS voices",
    "無法列出 Windows TTS 聲音": "Unable to list Windows TTS voices",
    "正在匯入 runtime": "Importing runtime",
    "runtime 匯入失敗": "Runtime import failed",
    "正在檢查更新": "Checking for updates",
    "更新檢查失敗": "Update check failed",
    "正在偵測硬體": "Detecting hardware",
    "硬體偵測失敗": "Hardware detection failed",
    "正在分析設定": "Analyzing settings",
    "自動優化失敗": "Automatic optimization failed",
    "正在下載離線翻譯模型": "Downloading offline translation models",
    "離線翻譯模型下載失敗": "Offline translation model download failed",
    "正在更新 commands.json": "Updating commands.json",
    "commands.json 更新失敗": "commands.json update failed",
    "正在測試 API": "Testing API",
    "API 測試失敗": "API test failed",
    "正在測試裝置音": "Testing device tone",
    "裝置音測試失敗": "Device tone test failed",
    "正在測試麥克風": "Testing microphone",
    "麥克風測試失敗": "Microphone test failed",
    "正在檢查啟動需求": "Checking startup requirements",
    "啟動檢查失敗": "Startup check failed",
    "正在測試 TTS": "Testing TTS",
    "TTS 測試已在進行": "A TTS test is already running",
    "TTS 測試失敗": "TTS test failed",
    "TTS 輸出測試完成": "TTS output test completed",
    "正在測試虛擬麥克風": "Testing virtual microphone",
    "虛擬麥克風測試已在進行": "A virtual microphone test is already running",
    "虛擬麥克風測試失敗": "Virtual microphone test failed",
    "虛擬麥克風已偵測到聲音": "Virtual microphone audio detected",
    "虛擬麥克風沒有偵測到聲音": "No virtual microphone audio detected",
    "正在測試喇叭": "Testing speaker",
    "喇叭測試已在進行": "A speaker test is already running",
    "喇叭測試失敗": "Speaker test failed",
    "喇叭已偵測到聲音": "Speaker audio detected",
    "喇叭目前沒有偵測到聲音": "No speaker audio detected",
    "麥克風音量 {level:.4f}": "Microphone level {level:.4f}",
    "設定已在啟動檢查期間變更；請重新按開始": "Settings changed during startup checks; press Start again",
    "啟動工作已在進行": "A startup task is already running",
    "啟動失敗：{error}": "Startup failed: {error}",
    "停止工作已在進行": "A stop task is already running",
    "停止失敗：{error}": "Stop failed: {error}",
    "不支援的來源或目標語言": "Unsupported source or target language",
    "來源與目標語言不可相同": "Source and target languages must differ",
    "runtime 不可用": "Runtime unavailable",
    "模型不完整或損毀": "Model is incomplete or corrupt",
    "找不到模型": "Model not found",
    "請下載或重新安裝模型：{model}": "Download or reinstall the model: {model}",
    "喇叭擷取已略過：和 TTS 輸出相同": "Speaker capture skipped because it matches the TTS output",
    "麥克風擷取已略過：和虛擬麥克風輸出相同": "Microphone capture skipped because it matches the virtual microphone output",
    "{source}：{error}": "{source}: {error}",
    "沒有字幕可複製": "No subtitles to copy",
    "字幕已複製": "Subtitles copied",
    "找不到 Windows TTS 聲音": "No Windows TTS voices found",
    "自動偵測來源語言時無法交換；請先選擇固定來源語言": "Languages cannot be swapped while source detection is automatic; select a fixed source language first",
    "啟用雲端 API？": "Enable cloud API?",
    "雲端 API 可能傳送語音或文字並產生費用。是否繼續？": "A cloud API may transmit audio or text and incur charges. Continue?",
    "雲端 API 未啟用": "Cloud API not enabled",
    "啟用本次對話紀錄？": "Enable conversation logs for this session?",
    "本次執行是否允許儲存設定中指定的對話內容？": "Allow this session to save the conversation content selected in settings?",
    "設定套用失敗：{error}": "Failed to apply settings: {error}",
    "{status}；相同工作已在進行": "{status}; the same task is already running",
    "已取消 {count} 個背景工作": "Cancelled {count} background tasks",
    "目前沒有可取消的背景工作": "There are no background tasks to cancel",
    "詞彙已加入": "Glossary term added",
    "沒有可修正的近期翻譯": "There is no recent translation to correct",
    "加入術語表？": "Add to glossary?",
    "是否將這個修正加入術語表？": "Add this correction to the glossary?",
    "翻譯修正未加入詞彙表": "Translation correction was not added to the glossary",
    "翻譯修正已加入詞彙表": "Translation correction added to the glossary",
    "選擇已解壓的 Faster-Whisper-XXL 資料夾": "Select the extracted Faster-Whisper-XXL folder",
    "runtime 不完整": "Runtime is incomplete",
    "缺少：{missing}": "Missing: {missing}",
    "runtime 已匯入；commands.json 已更新": "Runtime imported; commands.json updated",
    "沒有偵測到可鎖定的語言": "No language was detected to lock",
    "來源語言已鎖定：{language}": "Source language locked: {language}",
    "已套用場景：{scenario}": "Scenario applied: {scenario}",
    "設定已是建議值": "Settings already match the recommendation",
    "預覽自動優化": "Preview automatic optimization",
    "已保留原設定": "Original settings kept",
    "模型下載已在進行；可按「取消模型下載」": "A model download is already running; use Cancel model download",
    "正在下載模型 {model}": "Downloading model {model}",
    "前一個模型下載仍在結束中": "The previous model download is still stopping",
    "模型下載完成：{model}；版本與 SHA 完整性已驗證": "Model download completed: {model}; version and SHA verified",
    "目前沒有模型下載工作": "No model download is running",
    "正在取消模型下載；已下載部分可供稍後續傳": "Cancelling model download; downloaded data can be resumed later",
    "請先選擇來源語言": "Select a source language first",
    "下載離線翻譯模型前，請把「來源語言」改成固定語言。": "Select a fixed source language before downloading offline translation models.",
    "下載離線翻譯模型": "Download offline translation models",
    "將下載 {source} 與 {target} 的雙向 Argos Translate 模型。\n模型會儲存在程式資料夾的 models\\translation。": "Download bidirectional Argos Translate models for {source} and {target}.\nModels will be stored in the app models\\translation folder.",
    "離線翻譯模型下載完成：{count} 個": "Offline translation model download completed: {count}",
    "commands.json 已更新": "commands.json updated",
    "裝置音測試完成": "Device tone test completed",
    "字幕測試完成": "Subtitle test completed",
    "字幕已顯示": "Subtitles are visible",
    "已開啟修復說明": "Repair instructions opened",
    "自動優化有 {count} 項建議；請按「自動優化」預覽並確認": "Automatic optimization has {count} recommendations; use Auto optimize to review them",
    "快取已清除": "Cache cleared",
    "沒有可匯出的紀錄": "No logs are available to export",
    "字幕已匯出：{path}": "Subtitles exported: {path}",
    "紀錄已清除": "Logs cleared",
    "本機快取與紀錄已清除": "Local cache and logs cleared",
    "無法清除紀錄": "Unable to clear logs",
    "原文": "Original text",
    "譯文": "Translation",
    "請輸入修正翻譯：\n{source}": "Enter the corrected translation:\n{source}",
    "所有檔案": "All files",
    "套用 {count} 項自動優化建議？": "Apply {count} automatic optimization recommendations?",
    "確認清除外部紀錄": "Confirm deletion of external logs",
    "將從以下資料夾清除 {count} 個本程式紀錄檔：\n{path}\n\n其他檔案與子資料夾不會刪除。是否繼續？": "Delete {count} app log files from this folder:\n{path}\n\nOther files and subfolders will not be deleted. Continue?",
    "鎖定語言": "Lock language",
    "檢查更新": "Check for updates",
    "更新指令設定": "Update command settings",
    "開啟程式資料夾": "Open app folder",
    "開啟術語表": "Open glossary",
    "新增術語": "Add glossary term",
    "修正上次翻譯": "Correct last translation",
    "測試 API": "Test API",
    "測試裝置音": "Test device tone",
    "測試 TTS": "Test TTS",
    "測試虛擬麥克風": "Test virtual microphone",
    "測試喇叭": "Test speaker",
    "測試麥克風": "Test microphone",
    "取消背景工作": "Cancel background tasks",
    "測試字幕": "Test subtitles",
    "開始": "Start",
    "停止": "Stop",
    "離開": "Exit",
    "暫停/繼續": "Pause/resume",
    "虛擬麥克風靜音/取消": "Mute/unmute virtual microphone",
    "本機翻譯靜音/取消": "Mute/unmute local translation",
    "切換字幕": "Toggle subtitles",
    "切換語音": "Toggle speech",
    "切換喇叭": "Toggle speaker",
    "切換麥克風": "Toggle microphone",
    "複製字幕": "Copy subtitles",
    "修復喇叭音訊": "Fix speaker audio",
    "修復麥克風輸出": "Fix microphone output",
    "修復字幕": "Fix subtitles",
    "修復本機翻譯": "Fix local translation",
    "清除快取": "Clear cache",
    "開啟紀錄": "Open logs",
    "匯出字幕": "Export subtitles",
    "清除紀錄": "Clear logs",
    "清除本機資料": "Clear local data",
    "按住說話": "Push to talk",
    "就緒": "Ready",
    "系統預設": "System default",
    "遊戲語音": "Game voice",
    "Discord 聊天": "Discord chat",
    "遠端會議": "Remote meeting",
    "客服對話": "Customer service",
    "字幕顯示": "Subtitles only",
    "自己說話翻譯": "Translate my speech",
    "雙向翻譯": "Two-way translation",
    "正在重新整理裝置與模型": "Refreshing devices and models",
    "裝置與模型重新整理已在進行": "A device and model refresh is already running",
    "無法重新整理裝置與模型：{error}": "Unable to refresh devices and models: {error}",
    "裝置與模型已更新": "Devices and models updated",
    "正在檢查 runtime": "Checking runtime",
    "runtime 檢查失敗：{error}": "Runtime check failed: {error}",
    "runtime 已就緒；CPU：{cpu}；CUDA：{cuda}": "Runtime ready; CPU: {cpu}; CUDA: {cuda}",
    "可用": "available",
    "不可用": "unavailable",
    "找不到模型：{model}": "Model not found: {model}",
    "runtime 尚未就緒；請開啟 runtime 資料夾或匯入 runtime": "Runtime is not ready; open the runtime folder or import a runtime",
    "模式：翻譯 {provider}；TTS {tts_provider}": "Mode: translation {provider}; TTS {tts_provider}",
    "對話紀錄：{state}": "Conversation logs: {state}",
    "場景：{scenario}；來源 {source}；目標 {target}": "Scenario: {scenario}; source {source}; target {target}",
    "開啟": "on",
    "關閉": "off",
    "關閉視窗": "Close",
    "喇叭": "Speaker",
    "麥克風": "Microphone",
    "離線翻譯模型載入失敗：{error}": "Failed to load the offline translation model: {error}",
    "找不到 runtime：{missing}": "Runtime not found: {missing}",
    "沒有可用音訊裝置": "No audio device is available",
    "停止逾時：仍有 {count} 個背景工作": "Stop timed out; {count} background tasks are still running",
    "已停止": "Stopped",
    "已暫停": "Paused",
    "執行中": "Running",
    "虛擬麥克風已靜音": "Virtual microphone muted",
    "虛擬麥克風已取消靜音": "Virtual microphone unmuted",
    "本機翻譯播放已靜音": "Local translation playback muted",
    "本機翻譯播放已取消靜音": "Local translation playback unmuted",
    "{source}：翻譯失敗：{error}": "{source}: translation failed: {error}",
    "{source}：TTS 失敗：{error}": "{source}: TTS failed: {error}",
    "{source}延遲 {latency:.2f} 秒": "{source} latency {latency:.2f} seconds",
    "部分可用；{sources}擷取失敗；請停止後重新啟動": "Partially available; {sources} capture failed; stop and restart",
    "音訊降級；{sources}擷取恢復中": "Audio degraded; {sources} capture is recovering",
    "{source}擷取暫時失敗 [{code}]：{error}；第 {attempt} 次重試": "{source} capture temporarily failed [{code}]: {error}; retry {attempt}",
    "{source}擷取恢復中；第 {attempt} 次重試": "{source} capture is recovering; retry {attempt}",
    "{source}擷取已恢復": "{source} capture recovered",
    "{source}擷取失敗 [{code}]：{error}；請停止後重新啟動": "{source} capture failed [{code}]: {error}; stop and restart",
    "{source}：處理落後，已略過 {dropped} 段；佇列 {depth}/{maximum}": "{source}: processing is behind; skipped {dropped} segments; queue {depth}/{maximum}",
    "介面語言已變更；請重新啟動程式以完整套用": "Interface language changed; restart the app to apply it completely",
    "Google 驗證成功": "Google authentication succeeded",
    "有新版本可下載：{latest}（{url}）": "A new version is available: {latest} ({url})",
    "已是最新版本：{current}": "You are using the latest version: {current}",
    "已套用 {count} 項自動優化建議": "Applied {count} automatic optimization recommendations",
    "正在取得模型 {model} 的版本與檔案資訊": "Retrieving version and file information for model {model}",
    "正在下載模型 {model}：{percent:.1f}%（{downloaded:.1f}/{total:.1f} MB，{speed:.1f} MB/s）": "Downloading model {model}: {percent:.1f}% ({downloaded:.1f}/{total:.1f} MB, {speed:.1f} MB/s)",
    "模型 {model} 下載完成；版本 {revision}，SHA 完整性驗證成功": "Model {model} downloaded; version {revision}; SHA integrity verified",
    "雲端 API 模式": "Cloud API mode",
    "本機免費模式": "Free local mode",
    "延遲 {total:.2f} 秒": "Latency {total:.2f} seconds",
    "翻譯服務 {provider}": "Translation service {provider}",
    "費用 {risk}": "Cost {risk}",
    "可能": "possible",
    "否": "no",
    "偵測語言 {source} 模型分數 {score:.2f}（未校準）": "Detected language {source}; model score {score:.2f} (uncalibrated)",
    "語言模型分數 無法取得": "Language model score unavailable",
    "ASR 模型分數 {score:.2f}（平均 log probability，未校準）": "ASR model score {score:.2f} (mean log probability, uncalibrated)",
    "ASR 模型分數 無法取得": "ASR model score unavailable",
    "翻譯品質訊號 無法取得": "Translation quality signal unavailable",
    "翻譯品質訊號 {signal:.2f}（供應商訊號）": "Translation quality signal {signal:.2f} (provider signal)",
    "翻譯提示 可用": "Translation notice available",
    "ASR 延遲 {latency}": "ASR latency {latency}",
    "翻譯延遲 {latency}": "Translation latency {latency}",
    "TTS 延遲 {latency}": "TTS latency {latency}",
    "TTS 服務 {provider}": "TTS service {provider}",
    "本機": "Local",
}


DIAGNOSTIC_TITLES = {
    "runtime_missing": "Speech recognition runtime unavailable",
    "runtime_capabilities": "Runtime capabilities",
    "model_missing": "Speech recognition model not found",
    "model_corrupt": "Speech recognition model is incomplete or corrupt",
    "feedback_risk": "Audio feedback risk",
    "virtual_mic_route": "Virtual microphone output may be unconfigured",
    "virtual_mic_device_missing": "Virtual audio output not found",
    "virtual_mic_input_missing": "Virtual microphone input not found",
    "microphone_feedback_risk": "Microphone may recapture translated speech",
    "speaker_device_missing": "Speaker source not found",
    "microphone_device_missing": "Microphone not found",
    "cloud_credentials_missing": "Cloud credentials are missing",
    "offline_translation_model_missing": "Offline translation model not found",
    "local_translate_url_missing": "Local translation URL is not configured",
    "translation_empty": "Translation result was empty",
    "asr_model_score_available": "Speech recognition model score",
    "asr_model_score_unavailable": "Speech recognition model score unavailable",
    "translation_quality_unavailable": "Translation quality signal unavailable",
    "translation_quality_signal": "Translation provider quality signal",
    "translation_heuristic_warning": "Translation heuristic notice",
    "tts_no_sound": "TTS produced no sound",
    "tts_latency_high": "TTS latency is high",
    "virtual_mic_no_output": "Virtual microphone produced no sound",
    "asr_runtime_failed": "Speech recognition runtime failed",
    "ffmpeg_failed": "FFmpeg capture failed",
    "microphone_no_sound": "Microphone produced no sound",
    "speaker_no_sound": "Speaker capture produced no sound",
    "asr_latency_high": "Speech recognition is slow",
    "translation_latency_high": "Translation latency is high",
    "audio_queue_backlog": "Audio queue is falling behind",
    "subtitle_latency_high": "Subtitle latency is high",
    "language_model_score_low": "Language model score is low",
    "language_model_score_unavailable": "Language model score unavailable",
    "gpu_unavailable": "GPU is unsupported or unavailable",
    "gpu_low_vram": "GPU memory is insufficient",
    "auto_tune_recommended": "Automatic optimization is available",
    "recent_error": "Recent error",
}


def normalize_language(language: str | None) -> str:
    return language if language in SUPPORTED_LANGUAGES else "zh-TW"


def setup_guide_text(language: str | None) -> str:
    return SETUP_GUIDES[normalize_language(language)]


def translate(language: str | None, message: str, **values) -> str:
    language = normalize_language(language)
    template = message if language == "zh-TW" else ENGLISH[message]
    return template.format(**values)


def translate_known(language: str | None, message: str) -> str:
    return ENGLISH.get(message, message) if normalize_language(language) == "en" else message


def missing_translation_keys(messages, language: str) -> set[str]:
    return set() if normalize_language(language) == "zh-TW" else set(messages) - ENGLISH.keys()


def diagnostic_fields(language: str | None, code: str, action: str, title: str, detail: str, fix: str) -> tuple[str, str, str]:
    if normalize_language(language) == "zh-TW":
        return title, detail, fix
    english_title = DIAGNOSTIC_TITLES.get(code, code.replace("_", " ").capitalize())
    return english_title, f"Detected by diagnostic check: {code}.", f"Use the recommended action: {action.replace('_', ' ')}."
